using System.Collections.Generic;
using UnityEngine;

public class QuestionData : MonoBehaviour
{
    [System.Serializable]
    public class Question
    {
        public string topic;
        public string questionText;
        public bool isCorrect; // O면 true, X면 false
        public int level; // 1 ~ 10
    }

    public List<Question> questions = new List<Question>()
    {
        // Topic - 과학
        new Question { topic = "과학", questionText = "물은 0도에서 얼음으로 변한다.", isCorrect = true, level = 2 },
        new Question { topic = "과학", questionText = "태양은 행성이다.", isCorrect = false, level = 2 },
        new Question { topic = "과학", questionText = "모든 금속은 자성을 띤다.", isCorrect = false, level = 2 },
        new Question { topic = "과학", questionText = "빛은 소리보다 빠르게 이동한다.", isCorrect = true, level = 3 },
        new Question { topic = "과학", questionText = "산소는 사람의 생명 유지에 필수적인 기체이다.", isCorrect = true, level = 3 },
        new Question { topic = "과학", questionText = "물은 수소 원자 두 개와 산소 원자 한 개로 이루어져 있다.", isCorrect = true, level = 3 },
        new Question { topic = "과학", questionText = "지구의 대기는 주로 헬륨과 수소로 이루어져 있다.", isCorrect = false, level = 4 },
        new Question { topic = "과학", questionText = "전자기 스펙트럼에서 가시광선은 자외선보다 높은 에너지를 가진다.", isCorrect = false, level = 4 },
        new Question { topic = "과학", questionText = "뉴턴의 제1법칙은 '관성의 법칙'이라고 불린다.", isCorrect = true, level = 4 },
        new Question { topic = "과학", questionText = "지구의 자기장은 태양풍으로부터 지구를 보호하는 역할을 한다.", isCorrect = true, level = 5 },
        new Question { topic = "과학", questionText = "산성 용액은 pH 값이 7보다 크다.", isCorrect = false, level = 5 },
        new Question { topic = "과학", questionText = "원자의 중심에는 양성자와 중성자로 이루어진 원자핵이 있다.", isCorrect = true, level = 7 },
        new Question { topic = "과학", questionText = "엔트로피는 물질의 온도가 높아질수록 감소한다.", isCorrect = false, level = 7 },
        new Question { topic = "과학", questionText = "반물질은 물질과 충돌할 때 에너지를 방출한다.", isCorrect = true, level = 7 },
        new Question { topic = "과학", questionText = "DNA는 유전 정보를 저장하는 분자이다.", isCorrect = true, level = 5 },
        new Question { topic = "과학", questionText = "중성미자(neutrino)는 질량이 없는 입자로 간주된다.", isCorrect = false, level = 6 },
        new Question { topic = "과학", questionText = "태양에서 일어나는 핵융합 반응의 주요 연료는 수소이다.", isCorrect = true, level = 6 },
        new Question { topic = "과학", questionText = "상대성 이론에 따르면, 빛의 속도는 절대적으로 일정하다.", isCorrect = true, level = 6 },
        new Question { topic = "과학", questionText = "태양은 별이다.", isCorrect = true, level = 3 },
        new Question { topic = "과학", questionText = "지구는 평평하다.", isCorrect = false ,level = 2 },
        new Question { topic = "과학", questionText = "일반 상대성 이론에 따르면, 중력장은 공간과 시간을 휘게 만든다.", isCorrect = true, level = 9 },
        new Question { topic = "과학", questionText = "물은 H2O로 이루어져 있다.", isCorrect = true, level = 4 },
        new Question { topic = "과학", questionText = "사람은 도구 없이 스스로의 힘으로 날 수 있다.", isCorrect = false , level = 1 },
        new Question { topic = "과학", questionText = "빛은 파동과 입자의 성질을 동시에 가진다.", isCorrect = true, level = 8 },
        new Question { topic = "과학", questionText = "이론상으로 기체는 절대영도에서 부피가 0이 된다.", isCorrect = true, level = 8 },
        new Question { topic = "과학", questionText = "물은 100도에서 끓는다.", isCorrect = true, level = 2 },
        new Question { topic = "과학", questionText = "소리는 진공에서도 전달될 수 있다.", isCorrect = false, level = 3 },
        new Question { topic = "과학", questionText = "빛은 파동과 입자의 성질을 동시에 가진다.", isCorrect = true, level = 5 },
        new Question { topic = "과학", questionText = "플루토늄은 자연적으로 존재하는 원소이다.", isCorrect = false, level = 7 },
        new Question { topic = "과학", questionText = "사람은 산소가 없으면 살 수 없다.", isCorrect = true, level = 1 },
        new Question { topic = "과학", questionText = "대통일이론(GUT)은 자연계에서 존재하는 4가지 힘에서 중력을\n제외한 강력, 전자기력, 약력을 하나의 이론으로 설명하려 한다.", isCorrect = true, level = 10 },
        new Question { topic = "과학", questionText = "모든 새는 날 수 있다.", isCorrect = false, level = 1 },
        new Question { topic = "과학", questionText = "중력파는 시공간의 곡률 변화로 인해 발생하는 파동이다.", isCorrect = true, level = 8 },
        new Question { topic = "과학", questionText = "초전도체는 절대온도 0K에서만 저항이 0이 된다.", isCorrect = false, level = 8 },
        new Question { topic = "과학", questionText = "광자(photon)는 질량을 가지고 있다.", isCorrect = false, level = 8 },
        new Question { topic = "과학", questionText = "전자와 양성자는 같은 질량을 가진다.", isCorrect = false, level = 4 },
        new Question { topic = "과학", questionText = "인체에서 가장 많이 존재하는 원소는 산소이다.", isCorrect = true, level = 3 },
        new Question { topic = "과학", questionText = "초끈 이론에 따르면, 우주의 기본 구성 요소는 1차원적인 끈이다.", isCorrect = true, level = 10 },
        new Question { topic = "과학", questionText = "호킹 복사는 블랙홀이 에너지를 방출하면서 증발하는 현상이다.", isCorrect = true, level = 10 },
        new Question { topic = "과학", questionText = "전자기 이론을 제안한 과학자는 뉴턴이다.", isCorrect = false, level = 6 },
        new Question { topic = "과학", questionText = "태양의 빛이 지구에 도달하는 데 약 8분 20초가 걸린다.", isCorrect = true, level = 5 },
        new Question { topic = "과학", questionText = "모든 금속은 상온에서 고체 상태이다.", isCorrect = false, level = 4 },
        new Question { topic = "과학", questionText = "원자의 핵을 구성하는 양성자와 중성자는 서로 강한 핵력으로 결합되어 있다.", isCorrect = true, level = 8 },
        new Question { topic = "과학", questionText = "열역학 제2법칙에 따르면, 엔트로피는 항상 감소하는 방향으로 진행한다.", isCorrect = false, level = 8 },
        new Question { topic = "과학", questionText = "반도체는 온도가 낮아질수록 전기 전도성이 증가한다.", isCorrect = false, level = 8 },
        new Question { topic = "과학", questionText = "DNA는 단백질로 구성되어 있다.", isCorrect = false, level = 3 },
        new Question { topic = "과학", questionText = "지구의 중심부는 액체 상태이다.", isCorrect = true, level = 4 },
        new Question { topic = "과학", questionText = "양자 얽힘은 두 입자가 공간적으로 떨어져 있어도 서로 상태가 연관되는 현상이다.", isCorrect = true, level = 9 },
        new Question { topic = "과학", questionText = "절대온도 0K에서는 모든 분자의 운동이 완전히 멈춘다.", isCorrect = true, level = 9 },
        new Question { topic = "과학", questionText = "다중우주 이론은 현재 실험적으로 입증되었다.", isCorrect = false, level = 9 },
        new Question { topic = "과학", questionText = "탄소는 비금속 원소이다.", isCorrect = true, level = 5 },
        new Question { topic = "과학", questionText = "달은 지구를 돈다.", isCorrect = true, level = 1 },
        new Question { topic = "과학", questionText = "불은 물을 부으면 더 잘 탄다.", isCorrect = false, level = 1 },
        new Question { topic = "과학", questionText = "전자기파의 모든 스펙트럼에서 감마선이 가장 긴 파장을 가진다.", isCorrect = false, level = 9 },
        new Question { topic = "과학", questionText = "슈뢰딩거 방정식은 양자역학에서 입자의 운동을 기술하는 기본 방정식이다.", isCorrect = true, level = 9 },
        new Question { topic = "과학", questionText = "나무는 햇빛 없이도 성장할 수 있다.", isCorrect = false, level = 1 },
        new Question { topic = "과학", questionText = "초대칭 이론(SUSY)은 표준 모형의 모든 입자에 대해 동일한 질량을 가진 짝 입자가 존재한다고 예측한다.", isCorrect = true, level = 10 },
        new Question { topic = "과학", questionText = "수성은 태양계에서 가장 큰 행성이다.", isCorrect = false, level = 2 },
        new Question { topic = "과학", questionText = "진공에서는 어떤 전자기파도 전파될 수 없다.", isCorrect = false, level = 9 },
        new Question { topic = "과학", questionText = "소행성대는 화성과 목성 사이에 위치한다.", isCorrect = true, level = 4 },
        new Question { topic = "과학", questionText = "태양계에서 가장 온도가 높은 행성은 금성이다.", isCorrect = true, level = 5 },
        new Question { topic = "과학", questionText = "빛은 물질이 없는 공간을 통과할 수 없다.", isCorrect = false, level = 3 },
        new Question { topic = "과학", questionText = "토성의 고리는 대부분 얼음과 먼지로 이루어져 있다.", isCorrect = true, level = 4 },
        new Question { topic = "과학", questionText = "대부분의 바이러스는 스스로 에너지를 생성할 수 있다.", isCorrect = false, level = 6 },
        new Question { topic = "과학", questionText = "블랙홀의 중력은 빛조차 빠져나올 수 없을 정도로 강하다.", isCorrect = true, level = 7 },
        new Question { topic = "과학", questionText = "원자의 핵은 양성자와 중성자로 구성되어 있다.", isCorrect = true, level = 3 },
        new Question { topic = "과학", questionText = "양자장론에서 가상의 입자는 실험적으로 직접 검출할 수 있다.", isCorrect = false, level = 10 },
        new Question { topic = "과학", questionText = "음식물 소화는 주로 소장에서 이루어진다.", isCorrect = true, level = 5 },
        new Question { topic = "과학", questionText = "전기는 전자의 흐름에 의해 발생한다.", isCorrect = true, level = 4 },
        new Question { topic = "과학", questionText = "태양은 밤에 뜬다.", isCorrect = false, level = 1 },
        new Question { topic = "과학", questionText = "호킹 복사는 블랙홀이 발산하는 에너지로, 이론적으로 관측된 바 있다.", isCorrect = false, level = 10 },
        new Question { topic = "과학", questionText = "물고기는 물속에서 숨을 쉴 수 있다.", isCorrect = true, level = 1 },
        new Question { topic = "과학", questionText = "암흑물질은 주로 중입자로 구성되어 있다.", isCorrect = false, level = 10 },

        // Topic - 동물
        new Question { topic = "동물", questionText = "코끼리는 포유류이다.", isCorrect = true, level = 1 },
        new Question { topic = "동물", questionText = "타조는 날 수 있는 새이다.", isCorrect = false, level = 2 },
        new Question { topic = "동물", questionText = "박쥐는 유일하게 날 수 있는 포유류이다.", isCorrect = true, level = 3 },
        new Question { topic = "동물", questionText = "캥거루는 뒤로 걸을 수 있다.", isCorrect = false, level = 4 },
        new Question { topic = "동물", questionText = "북극곰의 피부는 검은색이다.", isCorrect = true, level = 6 },
        new Question { topic = "동물", questionText = "고양이는 초콜릿을 먹어도 괜찮다.", isCorrect = false, level = 8 },
        new Question { topic = "동물", questionText = "도마뱀은 꼬리를 스스로 자를 수 있다.", isCorrect = true, level = 3 },
        new Question { topic = "동물", questionText = "벌들은 춤으로 의사소통을 할 수 있다.", isCorrect = true, level = 5 },
        new Question { topic = "동물", questionText = "카멜레온은 피부 색깔을 감정 상태에 따라 바꿀 수 있다.", isCorrect = true, level = 7 },
        new Question { topic = "동물", questionText = "개미는 잠을 자지 않는다.", isCorrect = true, level = 10 },
        new Question { topic = "동물", questionText = "코알라는 유칼립투스 잎 이외의 음식도 자주 먹는다.", isCorrect = false, level = 4 },
        new Question { topic = "동물", questionText = "일부 개구리는 얼어붙어도 살아남을 수 있다.", isCorrect = true, level = 9 },
        new Question { topic = "동물", questionText = "토끼의 앞니는 평생 자라난다.", isCorrect = true, level = 3 },
        new Question { topic = "동물", questionText = "코뿔소의 뿔은 뼈로 이루어져 있다.", isCorrect = false, level = 5 },
        new Question { topic = "동물", questionText = "돌고래는 의사소통을 위해 고유한 이름을 사용한다.", isCorrect = true, level = 6 },
        new Question { topic = "동물", questionText = "타란툴라는 독이 없어 사람에게 무해하다.", isCorrect = false, level = 7 },
        new Question { topic = "동물", questionText = "카피바라는 설치류 중 가장 크다.", isCorrect = true, level = 4 },
        new Question { topic = "동물", questionText = "지렁이의 몸은 여러 개의 마디로 이루어져 있다.", isCorrect = true, level = 2 },
        new Question { topic = "동물", questionText = "부엉이는 낮에 활동하는 동물이다.", isCorrect = false, level = 1 },
        new Question { topic = "동물", questionText = "수달은 돌을 도구로 사용하는 몇 안 되는 동물 중 하나이다.", isCorrect = true, level = 6 },
        new Question { topic = "동물", questionText = "코끼리는 하루에 약 3시간만 잠을 잔다.", isCorrect = true, level = 9 },
        new Question { topic = "동물", questionText = "불가사리는 뇌가 없다.", isCorrect = true, level = 10 },
        new Question { topic = "동물", questionText = "고래는 물고기가 아니라 포유류이다.", isCorrect = true, level = 2 },
        new Question { topic = "동물", questionText = "코알라는 하루에 20시간 이상을 잔다.", isCorrect = true, level = 3 },
        new Question { topic = "동물", questionText = "하마의 땀은 붉은색을 띤다.", isCorrect = true, level = 5 },
        new Question { topic = "동물", questionText = "기린의 혀는 검푸른 색이다.", isCorrect = true, level = 6 },
        new Question { topic = "동물", questionText = "가오리는 전기를 발생시킬 수 있다.", isCorrect = false, level = 1 },
        new Question { topic = "동물", questionText = "카멜레온은 주변 환경에 따라 색이 변하는 능력이 있다.", isCorrect = true, level = 4 },
        new Question { topic = "동물", questionText = "코브라는 자신이 알을 낳은 후 새끼를 돌본다.", isCorrect = false, level = 8 },
        new Question { topic = "동물", questionText = "대왕오징어는 지구상에서 가장 큰 무척추동물 중 하나이다.", isCorrect = true, level = 9 },
        new Question { topic = "동물", questionText = "개미는 폐를 가지고 있다.", isCorrect = false, level = 3 },
        new Question { topic = "동물", questionText = "카멜레온의 눈은 서로 독립적으로 움직일 수 있다.", isCorrect = true, level = 5 },
        new Question { topic = "동물", questionText = "상어는 평생 동안 계속해서 이를 교체한다.", isCorrect = true, level = 10 },
        new Question { topic = "동물", questionText = "수달은 물속에서 숨을 쉬기 위해 아가미를 사용한다.", isCorrect = false, level = 1 },
        new Question { topic = "동물", questionText = "카피바라는 세계에서 가장 큰 설치류이다.", isCorrect = true, level = 4 },
        new Question { topic = "동물", questionText = "오리는 앞발가락이 서로 붙어있다.", isCorrect = true, level = 2 },
        new Question { topic = "동물", questionText = "낙타의 혹에는 물이 저장되어 있다.", isCorrect = false, level = 3 },
        new Question { topic = "동물", questionText = "해파리는 뇌가 없다.", isCorrect = true, level = 5 },
        new Question { topic = "동물", questionText = "고양이는 인간의 말을 이해할 수 없다.", isCorrect = false, level = 2 },
        new Question { topic = "동물", questionText = "코끼리는 절대로 점프할 수 없다.", isCorrect = true, level = 3 },
        new Question { topic = "동물", questionText = "불가사리는 다리가 잘려도 다시 자랄 수 있다.", isCorrect = true, level = 5 },
        new Question { topic = "동물", questionText = "하이에나는 개과 동물이다.", isCorrect = false, level = 8 },
        new Question { topic = "동물", questionText = "상어는 물 밖에서도 10분 이상 생존할 수 있다.", isCorrect = false, level = 9 },
        new Question { topic = "동물", questionText = "지네는 다리가 300개가 넘는 종이 있다.", isCorrect = true, level = 6 },
        new Question { topic = "동물", questionText = "거미는 곤충이다.", isCorrect = false, level = 4 },
        new Question { topic = "동물", questionText = "문어는 위협을 받을 때 다리를 스스로 절단할 수 있다.", isCorrect = true, level = 10 },
        new Question { topic = "동물", questionText = "인간의 심장은 네 개의 방으로 이루어져 있다.", isCorrect = true, level = 3 },
        new Question { topic = "동물", questionText = "인간의 뇌는 약 1.4kg의 무게를 가진다.", isCorrect = true, level = 5 },
        new Question { topic = "동물", questionText = "사람의 유전자는 100% 고유하다.", isCorrect = false, level = 4 },
        new Question { topic = "동물", questionText = "사람의 시력은 태어났을 때가 가장 완벽하다.", isCorrect = false, level = 5 },
        new Question { topic = "동물", questionText = "인간의 폐는 하나만 있어도 정상적으로 생활할 수 있다.", isCorrect = true, level = 7 },
        new Question { topic = "동물", questionText = "상어는 뼈가 아닌 연골로 이루어져 있다.", isCorrect = true, level = 8 },
        new Question { topic = "동물", questionText = "금붕어는 한 달 이상 지난 일을 기억할 수 없다.", isCorrect = false, level = 3 },
        new Question { topic = "동물", questionText = "모든 물고기는 아가미로만 호흡한다.", isCorrect = false, level = 6 },
        new Question { topic = "동물", questionText = "전기뱀장어는 600볼트 이상의 전기를 생성할 수 있다.", isCorrect = true, level = 9 },
        new Question { topic = "동물", questionText = "인간의 체온은 평균적으로 약 37°C이다.", isCorrect = true, level = 1 },
        new Question { topic = "동물", questionText = "어류 중 일부는 육지에서도 숨을 쉴 수 있다.", isCorrect = true, level = 7 },
        new Question { topic = "동물", questionText = "사람의 혈액형은 A, B, O 세 종류만 존재한다.", isCorrect = false, level = 4 },
        new Question { topic = "동물", questionText = "인간의 뇌는 전체 체중의 약 2%를 차지하지만, 에너지 소비량은 20%에 달한다.", isCorrect = true, level = 7 },
        new Question { topic = "동물", questionText = "사람은 하루 평균 2리터의 침을 생성한다.", isCorrect = true, level = 3 },
        new Question { topic = "동물", questionText = "인간의 눈은 1,000만 가지 이상의 색상을 구별할 수 있다.", isCorrect = true, level = 6 },
        new Question { topic = "동물", questionText = "사람의 손톱과 머리카락은 죽은 세포로 이루어져 있다.", isCorrect = true, level = 2 },
        new Question { topic = "동물", questionText = "물고기는 항상 차가운 피를 가지고 있다.", isCorrect = false, level = 4 },
        new Question { topic = "동물", questionText = "상어는 수명이 평균 5년이다.", isCorrect = false, level = 8 },
        new Question { topic = "동물", questionText = "물고기 중 일부는 육지에서도 숨을 쉴 수 있다.", isCorrect = true, level = 6 },
        new Question { topic = "동물", questionText = "사람은 270개 이상의 뼈를 가지고 태어나지만, 성장하면서 206개로 줄어든다.", isCorrect = true, level = 2 },
        new Question { topic = "동물", questionText = "금붕어는 청각을 가지고 있다.", isCorrect = true, level = 3 },
        new Question { topic = "동물", questionText = "사람의 피부는 체온 조절을 돕기 위해 땀을 분비한다.", isCorrect = true, level = 4 },
        new Question { topic = "동물", questionText = "대부분의 물고기는 수명을 1년 이하로 산다.", isCorrect = false, level = 9 },
        new Question { topic = "동물", questionText = "해마는 수컷이 새끼를 낳는다.", isCorrect = true, level = 5 },
        new Question { topic = "동물", questionText = "인간의 심장은 하루에 약 10만 번 뛴다.", isCorrect = true, level = 7 },
        new Question { topic = "동물", questionText = "코끼리는 하루에 약 70리터 이상 물을 마신다.", isCorrect = true, level = 6 },
        new Question { topic = "동물", questionText = "오리너구리는 알을 낳는 포유류이다.", isCorrect = true, level = 5 },
        new Question { topic = "동물", questionText = "악어는 입을 벌릴 때보다 닫을 때 더 강한 힘을 사용한다.", isCorrect = false, level = 8 },
        new Question { topic = "동물", questionText = "코알라는 유칼립투스 잎에 포함된 독을 해독할 수 있다.", isCorrect = true, level = 4 },
        new Question { topic = "동물", questionText = "늑대는 무리 생활을 하지 않고 단독으로 사냥한다.", isCorrect = false, level = 3 },
        new Question { topic = "동물", questionText = "문어는 심장이 2개 이상 있다.", isCorrect = true, level = 9 },
        new Question { topic = "동물", questionText = "펭귄은 남극에서만 서식한다.", isCorrect = false, level = 4 },
        new Question { topic = "동물", questionText = "고양이는 땀샘이 발바닥에만 있다.", isCorrect = true, level = 5 },
        new Question { topic = "동물", questionText = "불가사리는 심장이 2개 있다.", isCorrect = false, level = 10 },
        new Question { topic = "동물", questionText = "고래는 물속에서 숨을 쉬기 위해 아가미를 사용한다.", isCorrect = false, level = 3 },
        new Question { topic = "동물", questionText = "개미는 자기 몸무게의 50배까지 들 수 있다.", isCorrect = true, level = 8 },

        // Topic - 세계
        new Question { topic = "세계", questionText = "일본의 수도는 도쿄이다.", isCorrect = true, level = 1 },
        new Question { topic = "세계", questionText = "프랑스의 대표적인 음식 중 하나는 스시이다.", isCorrect = false, level = 2 },
        new Question { topic = "세계", questionText = "브라질은 남아메리카 대륙에 위치해 있다.", isCorrect = true, level = 3 },
        new Question { topic = "세계", questionText = "이집트에는 피라미드가 존재하지 않는다.", isCorrect = false, level = 4 },
        new Question { topic = "세계", questionText = "세계에서 가장 많은 인구를 가진 나라는 인도이다.", isCorrect = true, level = 5 },
        new Question { topic = "세계", questionText = "스위스는 유럽연합(EU) 회원국이다.", isCorrect = false, level = 6 },
        new Question { topic = "세계", questionText = "대한민국의 전통 의상은 기모노이다.", isCorrect = false, level = 8 },
        new Question { topic = "세계", questionText = "로마 제국은 기원전 1세기에 멸망하였다.", isCorrect = false, level = 9 },
        new Question { topic = "세계", questionText = "노르웨이는 석유 수출로 경제를 발전시킨 나라 중 하나이다.", isCorrect = true, level = 10 },
        new Question { topic = "세계", questionText = "멕시코의 전통 음식 중 하나는 타코이다.", isCorrect = true, level = 2 },
        new Question { topic = "세계", questionText = "캐나다의 공용어는 영어와 프랑스어이다.", isCorrect = true, level = 4 },
        new Question { topic = "세계", questionText = "독일의 수도는 베를린이다.", isCorrect = true, level = 3 },
        new Question { topic = "세계", questionText = "칠레는 남아메리카에서 가장 넓은 나라이다.", isCorrect = false, level = 7 },
        new Question { topic = "세계", questionText = "중국의 수도는 베이징이다.", isCorrect = true, level = 1 },
        new Question { topic = "세계", questionText = "에펠탑은 독일 베를린에 위치해 있다.", isCorrect = false, level = 2 },
        new Question { topic = "세계", questionText = "남극은 세계에서 가장 추운 대륙이다.", isCorrect = true, level = 4 },
        new Question { topic = "세계", questionText = "스페인의 전통 춤 중 하나는 플라멩코이다.", isCorrect = true, level = 5 },
        new Question { topic = "세계", questionText = "일인당 연간 커피 소비량이 가장 많은 나라는 핀란드이다.", isCorrect = true, level = 6 },
        new Question { topic = "세계", questionText = "호주의 수도는 시드니이다.", isCorrect = false, level = 8 },
        new Question { topic = "세계", questionText = "세계에서 가장 작은 나라는 모나코이다.", isCorrect = false, level = 9 },
        new Question { topic = "세계", questionText = "몽골 제국은 역사상 가장 넓은 연속된 영토를 가졌던 제국이다.", isCorrect = true, level = 10 },
        new Question { topic = "세계", questionText = "아르헨티나는 축구와 탱고로 유명한 나라이다.", isCorrect = true, level = 2 },
        new Question { topic = "세계", questionText = "사우디아라비아는 석유 생산량이 세계에서 가장 많은 나라이다.", isCorrect = false, level = 5 },
        new Question { topic = "세계", questionText = "이탈리아의 수도는 마드리드이다.", isCorrect = false, level = 3 },
        new Question { topic = "세계", questionText = "한국과 일본은 같은 언어를 사용한다.", isCorrect = false, level = 7 },
        new Question { topic = "세계", questionText = "나이지리아는 아프리카에서 인구가 가장 많은 나라이다.", isCorrect = true, level = 6 },
        new Question { topic = "세계", questionText = "프랑스의 대표적인 음식 중 하나는 크루아상이다.", isCorrect = true, level = 1 },
        new Question { topic = "세계", questionText = "영국은 유럽 연합(EU) 회원국이다.", isCorrect = false, level = 3 },
        new Question { topic = "세계", questionText = "일본의 수도는 교토이다.", isCorrect = false, level = 2 },
        new Question { topic = "세계", questionText = "러시아는 세계에서 가장 큰 나라이다.", isCorrect = true, level = 4 },
        new Question { topic = "세계", questionText = "세계에서 가장 높은 산은 에베레스트산이다.", isCorrect = true, level = 3 },
        new Question { topic = "세계", questionText = "이집트의 피라미드는 고대 로마 시대에 지어졌다.", isCorrect = false, level = 5 },
        new Question { topic = "세계", questionText = "노르웨이는 오로라를 볼 수 있는 나라 중 하나이다.", isCorrect = true, level = 6 },
        new Question { topic = "세계", questionText = "브라질의 공식 언어는 스페인어이다.", isCorrect = false, level = 5 },
        new Question { topic = "세계", questionText = "스위스는 초콜릿과 시계로 유명한 나라이다.", isCorrect = true, level = 4 },
        new Question { topic = "세계", questionText = "남아프리카공화국의 수도는 하나뿐이다.", isCorrect = false, level = 7 },
        new Question { topic = "세계", questionText = "쿠바는 미국과 국경을 맞대고 있다.", isCorrect = false, level = 6 },
        new Question { topic = "세계", questionText = "이스탄불은 터키의 수도이다.", isCorrect = false, level = 9 },
        new Question { topic = "세계", questionText = "캐나다의 수도는 오타와이다.", isCorrect = true, level = 2 },
        new Question { topic = "세계", questionText = "중국에서 사용되는 공식 언어는 광동어이다.", isCorrect = false, level = 3 },
        new Question { topic = "세계", questionText = "아르헨티나는 남반구에 위치한 나라이다.", isCorrect = true, level = 4 },
        new Question { topic = "세계", questionText = "이탈리아의 수도는 밀라노이다.", isCorrect = false, level = 2 },
        new Question { topic = "세계", questionText = "호주는 세계에서 여섯 번째로 큰 나라이다.", isCorrect = true, level = 6 },
        new Question { topic = "세계", questionText = "핀란드는 북유럽에 위치한 나라이다.", isCorrect = true, level = 3 },
        new Question { topic = "세계", questionText = "독일의 공용어 중 하나는 프랑스어이다.", isCorrect = false, level = 4 },
        new Question { topic = "세계", questionText = "브라질은 남미에서 가장 큰 나라이다.", isCorrect = true, level = 5 },
        new Question { topic = "세계", questionText = "사우디아라비아는 이슬람교를 국교로 하는 나라이다.", isCorrect = true, level = 7 },
        new Question { topic = "세계", questionText = "대한민국과 북한은 같은 시각대를 사용한다.", isCorrect = false, level = 8 },
        new Question { topic = "세계", questionText = "페루에는 마추픽추 유적이 있다.", isCorrect = true, level = 6 },
        new Question { topic = "세계", questionText = "인도의 대표적인 전통 의상은 한복이다.", isCorrect = false, level = 3 },
        new Question { topic = "세계", questionText = "멕시코는 스페인어를 공식 언어로 사용한다.", isCorrect = true, level = 4 },
        new Question { topic = "세계", questionText = "아이슬란드는 유럽연합(EU) 회원국이다.", isCorrect = false, level = 9 },
        new Question { topic = "세계", questionText = "스위스는 공식적으로 수도가 없다.", isCorrect = true, level = 7 },
        new Question { topic = "세계", questionText = "일본의 국기는 흰색 바탕에 파란 원이 그려져 있다.", isCorrect = false, level = 2 },
        new Question { topic = "세계", questionText = "그리스는 유럽연합(EU) 회원국이다.", isCorrect = true, level = 5 },
        new Question { topic = "세계", questionText = "몽골은 육지로 둘러싸인 내륙국이다.", isCorrect = true, level = 4 },
        new Question { topic = "세계", questionText = "미국의 독립기념일은 7월 4일이다.", isCorrect = true, level = 3 },
        new Question { topic = "세계", questionText = "사모아는 아프리카에 위치한 나라이다.", isCorrect = false, level = 8 },
        new Question { topic = "세계", questionText = "이집트의 수도는 카이로이다.", isCorrect = true, level = 3 },
        new Question { topic = "세계", questionText = "남극 대륙에는 영구적으로 거주(상주)하는 인구가 1만 명 이상이다.", isCorrect = false, level = 8 },
        new Question { topic = "세계", questionText = "쿠바는 카리브해에 위치한 섬나라이다.", isCorrect = true, level = 6 },
        new Question { topic = "세계", questionText = "아랍에미리트의 수도는 두바이이다.", isCorrect = false, level = 4 },
        new Question { topic = "세계", questionText = "나일강은 세계에서 가장 긴 강이다.", isCorrect = true, level = 5 },
        new Question { topic = "세계", questionText = "노르웨이는 북유럽 국가이다.", isCorrect = true, level = 3 },
        new Question { topic = "세계", questionText = "아프리카 대륙에는 50개 이상의 나라가 있다.", isCorrect = true, level = 6 },
        new Question { topic = "세계", questionText = "태평양은 세계에서 가장 큰 바다이다.", isCorrect = true, level = 3 },
        new Question { topic = "세계", questionText = "남극 대륙에는 사막이 존재하지 않는다.", isCorrect = false, level = 7 },
        new Question { topic = "세계", questionText = "유럽 대륙의 가장 큰 나라는 프랑스이다.", isCorrect = false, level = 5 },
        new Question { topic = "세계", questionText = "대서양은 태평양보다 면적이 크다.", isCorrect = false, level = 4 },
        new Question { topic = "세계", questionText = "세계에서 가장 작은 대륙은 오세아니아이다.", isCorrect = true, level = 3 },
        new Question { topic = "세계", questionText = "북극해는 5대양 중에서 가장 작은 바다이다.", isCorrect = true, level = 5 },
        new Question { topic = "세계", questionText = "남미 대륙에서 가장 넓은 국가는 아르헨티나이다.", isCorrect = false, level = 6 },
        new Question { topic = "세계", questionText = "에베레스트산은 아시아 대륙에 위치해 있다.", isCorrect = true, level = 2 },
        new Question { topic = "세계", questionText = "그린란드는 아시아 대륙에 속해 있다.", isCorrect = false, level = 4 },
        new Question { topic = "세계", questionText = "인도양은 5대양 중 세 번째로 큰 바다이다.", isCorrect = true, level = 6 },
        new Question { topic = "세계", questionText = "아마존강은 아프리카 대륙에 존재한다.", isCorrect = false, level = 2 },
        new Question { topic = "세계", questionText = "빙하의 대부분은 남극과 그린란드에 존재한다.", isCorrect = true, level = 4 },
        new Question { topic = "세계", questionText = "북아메리카에는 20개 이상의 나라가 있다.", isCorrect = true, level = 6 },
        new Question { topic = "세계", questionText = "사우디아라비아에는 영구적인 강이 존재하지 않는다.", isCorrect = true, level = 7 },
        new Question { topic = "세계", questionText = "시베리아는 남미 대륙에 위치한 지역이다.", isCorrect = false, level = 3 },
        new Question { topic = "세계", questionText = "아시아는 세계에서 가장 큰 대륙이다.", isCorrect = true, level = 2 },
        new Question { topic = "세계", questionText = "유럽과 아시아의 경계는 우랄산맥이다.", isCorrect = true, level = 5 },
        new Question { topic = "세계", questionText = "북극해는 일 년 내내 얼어 있다.", isCorrect = false, level = 6 },
        new Question { topic = "세계", questionText = "나라가 가장 많은 대륙은 아프리카이다.", isCorrect = true, level = 5 },
        new Question { topic = "세계", questionText = "호주는 세계에서 가장 작은 나라이다.", isCorrect = false, level = 3 },
        new Question { topic = "세계", questionText = "남아메리카에는 20개 이상의 나라가 있다.", isCorrect = false, level = 4 },
        new Question { topic = "세계", questionText = "세계에서 가장 높은 폭포는 나이아가라 폭포이다.", isCorrect = false, level = 6 },
        new Question { topic = "세계", questionText = "그랜드캐니언은 유럽 대륙에 위치해 있다.", isCorrect = false, level = 2 },
        new Question { topic = "세계", questionText = "대서양은 태평양보다 짠물 농도가 높다.", isCorrect = true, level = 7 },
        new Question { topic = "세계", questionText = "마다가스카르는 아프리카 대륙에 속한 섬나라이다.", isCorrect = true, level = 5 },
        new Question { topic = "세계", questionText = "국제 표준시(UTC+0)는 영국의 그리니치 천문대를 기준으로 한다.", isCorrect = true, level = 10 },
        new Question { topic = "세계", questionText = "모든 유럽 연합(EU) 회원국은 유로(EUR)를 공식 통화로 사용한다.", isCorrect = false, level = 10 },
        new Question { topic = "세계", questionText = "지구상에서 가장 면적이 넓은 사막은 사하라 사막이다.", isCorrect = false, level = 10 }, // 남극이 가장 큼
        new Question { topic = "세계", questionText = "현재까지 공식적으로 인정된 국가의 수는 200개를 초과한다.", isCorrect = false, level = 10 }, // UN 기준 193개
        new Question { topic = "세계", questionText = "로마 제국은 서로마 제국과 동로마 제국으로 분리된 후, 서로마 제국이 더 오래 존속했다.", isCorrect = false, level = 10 },
        new Question { topic = "세계", questionText = "몽골 제국의 전성기 당시, 세계 역사상 가장 넓은 단일 제국을 형성했다.", isCorrect = true, level = 10 },
        new Question { topic = "세계", questionText = "전 세계에서 가장 많이 사용되는 언어는 영어이다.", isCorrect = false, level = 10 }, // 중국어(만다린어)
        new Question { topic = "세계", questionText = "대서양에는 '대서양 중앙 해령'이라는 거대한 해저 산맥이 존재한다.", isCorrect = true, level = 10 },
        new Question { topic = "세계", questionText = "대한민국과 북한은 공식적으로 '전쟁 상태'를 끝낸 평화협정을 체결한 적이 있다.", isCorrect = false, level = 10 }, // 정전협정만 체결
        new Question { topic = "세계", questionText = "세계에서 인구 밀도가 가장 높은 나라는 방글라데시이다.", isCorrect = false, level = 10 }, // 모나코가 1위
        new Question { topic = "세계", questionText = "아마존 강은 세계에서 가장 긴 강이다.", isCorrect = false, level = 10 }, // 나일강이 1위
        new Question { topic = "세계", questionText = "바티칸 시국은 세계에서 유일하게 공식적인 철도가 없는 나라이다.", isCorrect = false, level = 10 }, // 철도 있음
        new Question { topic = "세계", questionText = "남극은 국제적으로 어떤 국가의 영토로도 인정받지 않는다.", isCorrect = true, level = 10 },
        new Question { topic = "세계", questionText = "세계에서 가장 깊은 해구는 필리핀 해구이다.", isCorrect = false, level = 10 }, // 마리아나 해구가 가장 깊음
        new Question { topic = "세계", questionText = "세계 최초의 민주주의 국가는 고대 로마 공화국이었다.", isCorrect = false, level = 10 }, // 고대 아테네

        // 법률
        new Question { topic = "법률", questionText = "뇌물죄는 공무원만이 처벌 대상이 된다.", isCorrect = false, level = 8 },
        new Question { topic = "법률", questionText = "강도죄와 절도죄는 피해자의 반응과 관계없이 동일한 처벌을 받는다.", isCorrect = false, level = 9 },
        new Question { topic = "법률", questionText = "마약 범죄는 단순 소지와 유통이 동일한 처벌을 받는다.", isCorrect = false, level = 6 },
        new Question { topic = "법률", questionText = "보이스 피싱에 가담한 사람은 직접 돈을 받지 않아도 공범으로 처벌받을 수 있다.", isCorrect = true, level = 7 },
        new Question { topic = "법률", questionText = "스마트 계약을 이용한 금융 사기는 법적으로 처벌할 수 없다.", isCorrect = false, level = 2 },
        new Question { topic = "법률", questionText = "국제적인 해킹 범죄는 범인이 속한 국가에서만 처벌할 수 있다.", isCorrect = false, level = 4 },
        new Question { topic = "법률", questionText = "불법 도박은 온라인에서 이루어진 경우 처벌이 불가능하다.", isCorrect = false, level = 4 },
        new Question { topic = "법률", questionText = "조직 범죄에 가담한 모든 사람은 동일한 형량을 받는다.", isCorrect = false, level = 9 },
        new Question { topic = "법률", questionText = "미국과 EU에서는 개인정보 보호법 위반이 기업에 대해 매우 강한 처벌을 부과할 수 있다.", isCorrect = true, level = 10 },
        new Question { topic = "법률", questionText = "일본법에서는 살인죄의 최소 형량이 징역 5년이다.", isCorrect = true, level = 7 },
        new Question { topic = "법률", questionText = "미국 일부 주에서는 절도죄로 신체를 절단하는 형벌이 존재한다.", isCorrect = false, level = 9 },
        new Question { topic = "법률", questionText = "독일에서는 명예훼손죄로 인해 징역형을 선고받을 수 있다.", isCorrect = true, level = 6 },
        new Question { topic = "법률", questionText = "프랑스에서는 16세 미만의 아동을 체벌하는 것이 법적으로 금지되어 있다.", isCorrect = true, level = 5 },
        new Question { topic = "법률", questionText = "사우디아라비아에서는 간통죄로 최고 사형까지 선고될 수 있다.", isCorrect = true, level = 10 },
        new Question { topic = "법률", questionText = "캐나다에서 여가용 마리화나 소지는 불법이다.", isCorrect = false, level = 4 },
        new Question { topic = "법률", questionText = "스위스에서는 속도 제한을 초과하면 차량을 압수당할 수 있다.", isCorrect = true, level = 8 },
        new Question { topic = "법률", questionText = "대한민국에서는 음주운전 초범도 무조건 징역형을 선고받는다.", isCorrect = false, level = 5 },
        new Question { topic = "법률", questionText = "미국에서는 연방정부 차원에서 모든 주에서 사형제가 시행되고 있다.", isCorrect = false, level = 8 },
        new Question { topic = "법률", questionText = "노르웨이에서는 대량살상을 제외하면 최고 형량이 21년을 넘지 않는다.", isCorrect = true, level = 7 },
        new Question { topic = "법률", questionText = "호주에서는 공공장소에서 알몸으로 산책하는 것이 불법이 아니다.", isCorrect = false, level = 6 },
        new Question { topic = "법률", questionText = "네덜란드에서는 경범죄자의 신원을 공개하는 것이 법적으로 금지되어 있다.", isCorrect = true, level = 7 },
        new Question { topic = "법률", questionText = "스웨덴에서는 경찰이 허락 없이 개인의 통신을 감청할 수 있다.", isCorrect = false, level = 9 },
        new Question { topic = "법률", questionText = "네덜란드에서는 모든 마약이 합법이다.", isCorrect = false, level = 5 },
        new Question { topic = "법률", questionText = "사우디아라비아에서는 도둑질을 하면 손을 절단하는 형벌이 존재한다.", isCorrect = true, level = 8 },
        new Question { topic = "법률", questionText = "독일에서는 탈옥을 시도하는 것이 합법이다.", isCorrect = true, level = 7 },
        new Question { topic = "법률", questionText = "미국 텍사스에서는 말에게 술을 먹이는 것이 불법이다.", isCorrect = false, level = 6 },
        new Question { topic = "법률", questionText = "프랑스에서는 돼지에게 '나폴레옹'이라는 이름을 붙이는 것이 아직도 불법이다.", isCorrect = false, level = 3 },
        new Question { topic = "법률", questionText = "일본에서는 경찰이 목적과 이유를 밝히지 않고 시민의 가방을 검사할 수 있다.", isCorrect = false, level = 7 },
        new Question { topic = "법률", questionText = "싱가포르에서는 도시 미관의 이유 때문에 껌을 씹는 행위는 불법이다.", isCorrect = true, level = 6 },
        new Question { topic = "법률", questionText = "캐나다에서는 동전 25개 이상을 한 번에 사용하는 것이 불법이다.", isCorrect = true, level = 6 },
        new Question { topic = "법률", questionText = "중국에서는 성인도 온라인 게임을 3시간 이상 하면 처벌받는다.", isCorrect = false, level = 4 },
        new Question { topic = "법률", questionText = "러시아에서는 이슬람식 히잡을 착용하는 것이 불법이다.", isCorrect = false, level = 6 },
        new Question { topic = "법률", questionText = "이탈리아의 도시 베네치아에서는 비둘기에게 먹이를 주는 것이 불법이다.", isCorrect = true, level = 4 },
        new Question { topic = "법률", questionText = "미국 콜로라도주에서는 음주 후 말을 타는 것이 불법이다.", isCorrect = true, level = 5 },
        new Question { topic = "법률", questionText = "인도에서는 공공장소에서 애정을 표현하는 것이 법적으로 금지되어 있다.", isCorrect = false, level = 7 },
        new Question { topic = "법률", questionText = "멕시코에서는 경찰이 뇌물을 받을 경우, 정해진 일부만 반환한다면 법적제재를 받지 않는다.", isCorrect = false, level = 7 },
        new Question { topic = "법률", questionText = "프랑스에서는 허가받지 않고 버스에서 피아노를 연주하는 것이 불법이다.", isCorrect = true, level = 4 },
        new Question { topic = "법률", questionText = "남아프리카공화국에서는 곰 인형을 소유하는 것이 금지되어 있다.", isCorrect = false, level = 3 },
        new Question { topic = "법률", questionText = "덴마크에서는 차를 타기 전에 차량 밑에 사람이 있는지 확인해야 한다.", isCorrect = false, level = 8 },
        new Question { topic = "법률", questionText = "이란에서는 바비 인형을 판매하는 것이 불법이다.", isCorrect = true, level = 7 },
        new Question { topic = "법률", questionText = "싱가포르에서는 공공 화장실 사용 후 물을 내리지 않으면 벌금을 부과받을 수 있다.", isCorrect = true, level = 6 },
        new Question { topic = "법률", questionText = "미국 플로리다에서는 자동차를 후진할 때 창문을 열고 있어야 한다.", isCorrect = false, level = 5 },
        new Question { topic = "법률", questionText = "이스라엘에서는 주일(안식일)에 엘리베이터 버튼을 직접 눌러서는 안 된다.", isCorrect = true, level = 7 },
        new Question { topic = "법률", questionText = "캐나다에서는 마술사 행세 금지법이라는 것이 존재했었다.", isCorrect = true, level = 9 },
        new Question { topic = "법률", questionText = "독일의 고속도로인 아우토반에서는 주행 중 연료가 떨어지면 벌금이 부과될 수 있다.", isCorrect = true, level = 8 },
        new Question { topic = "법률", questionText = "태국에서는 공공장소에서 속옷을 입지 않으면 벌금을 부과받을 수 있다.", isCorrect = false, level = 6 },
        new Question { topic = "법률", questionText = "스페인에서는 공원에서 낮잠을 자는 것이 법적으로 금지되어 있다.", isCorrect = false, level = 4 },
        new Question { topic = "법률", questionText = "오스트리아에서는 강아지에게 특정한 헤어스타일을 하면 벌금을 내야 한다.", isCorrect = false, level = 3 },
        new Question { topic = "법률", questionText = "미국 플로리다에서는 야생 악어에게 함부로 먹이를 주면 안된다.", isCorrect = true, level = 5 },
        new Question { topic = "법률", questionText = "미국 애리조나에서는 선인장을 자르면 징역 25년형에 처해질 수 있다", isCorrect = true, level = 7 },
        new Question { topic = "법률", questionText = "이탈리아 도시인 밀라노에서는 인상을 쓰고 거리를 활보하면 벌금이 부과되지만, 병원 직원에겐 벌금이 청구되지 않는다.", isCorrect = true, level = 8 },
    };
}